language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - name: Ubuntu 16.04.6 LTS + g++-6 
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      script: 
         - lsb_release -a
         - mkdir Bin
         - cd Bin
         - cmake .. -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6
         - make

    # works on Precise and Trusty
    - name: Ubuntu 16.04.6 LTS + g++-7 
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script: 
         - mkdir Bin
         - cd Bin
         - cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7
         - make
    
    - name: Ubuntu 16.04.6 LTS + clang++-5.0
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      compiler: clang
      sudo: required
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      script: 
         - mkdir Bin
         - cd Bin
         - cmake .. -DCMAKE_C_COMPILER=clang-5.0 -DCMAKE_CXX_COMPILER=clang++-5.0
         - make
        
        # works on Trusty
    - name: Ubuntu 16.04.6 LTS + clang++-6.0
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
      compiler: clang
      sudo: required
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      script: 
         - mkdir Bin
         - cd Bin
         - cmake .. 
         - make
        
before_install:
    - eval "${MATRIX_EVAL}"