language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - name: Ubuntu 16.04.6 LTS + g++-6 
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      script: 
        - sh Scripts/travis_ci_linux.sh

    # works on Precise and Trusty
    - name: Ubuntu 16.04.6 LTS + g++-7 
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script: 
        - sh Scripts/travis_ci_linux.sh
    
    - name: Ubuntu 16.04.6 LTS + clang++-5.0
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      compiler: clang
      sudo: required
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      script: 
        - sh Scripts/travis_ci_linux.sh
        
        # works on Trusty
    - name: Ubuntu 16.04.6 LTS + clang++-6.0
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
      compiler: clang
      sudo: required
      dist: trusty
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      script: 
        - sh Scripts/travis_ci_linux.sh
        
before_install:
    - eval "${MATRIX_EVAL}"